name: push

on:
  push:
    branches-ignore:
      - 'refs/tags/v'

jobs:
  py39_checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Make checks on py-3.9
        uses: ./.github/workflows/reusable/py39.yml
